import graph
g = graph.Graph()
g.addEdge(('A','B',3))
g.addEdge(('A','C',4))
g.addEdge(('B','C',0.5))
g.addEdge(('D','A',0.1))
g.addEdge(('F','D',0.1))
g.addEdge(('C','F',0.1))
g.addEdge(('A','G',2))
g.addEdge(('C','G',4))
g.print()
print(g.djikstra('A','C'))
